server:
  port: 4040
spring:
  mvc:
    view:
      prefix: /WEB-INF/pages/
      suffix: .jsp
  application:
    name: donation-details

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka